# Generated by Django 4.1.2 on 2022-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrgtrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitars',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guitars',
            name='title',
            field=models.CharField(default='I-Am-A-Guitar', max_length=200),
        ),
    ]
